name: Generate HTML tables

on:
  workflow_dispatch:
  push:
    branches:
    - "master"
  schedule:
    # Each month on 3rd at 03:03
    - cron: "3 3 3 * *"
    # After FOSDEM check more often as authors accept videos of their talks
    - cron: "3 * * 2 *"

jobs:
  generate-and-deploy:
    permissions:
      contents: read
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Generate pages
        run: |
          upto_year=$(date +%Y)

          # December has schedule for next year so start using it
          if [ $(date +%m) == "12" ]; then
            upto_year=$(($upto_year + 1))
          fi

          years=`seq 2012 ${upto_year}`

          mkdir -p out
          for year in $years
          do
            curl -L -s https://fosdem.org/${year}/schedule/xml -o ${year}.xml

            python3 parser.py ${year}.xml >out/${year}.html
          done

          python parser.py 20*.xml > out/videoyears.html

          cd out
          ln -sf ${upto_year}.html index.html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
